### ISSUE TITLE
Improve the UI of 'history' section

### ISSUE THREAD

**Issue by annu12340** [annu12340/CS50-Final-Project#1]
Modify the UI of the history section

**Comment by esla-ahme** [comment]
@annu12340  please assign this issue to me. I will try my best to improve it.

Regards
Eslam

**Comment by chetas411** [comment]
@annu12340 what are the installation steps to run the app on local machine?
Hey @chetas I have raised it as an issue 

Steps
1. Clone the repo
2. Run ```pip install -r requirements.txt``` command

**Comment by esla-ahme** [comment]
server keeps response with this msg `('content is ', '{"Error Message" : "Invalid API KEY. Please retry or visit our documentation to create one FREE https://financialmodelingprep.com/developer/docs"}') `
I get my api key where should I add it?

**Comment by annu12340** [comment]
> @annu12340 please assign this issue to me. I will try my best to improve it.
> 
> Regards
> Eslam

Hey @esla-ahme 👋

**Comment by annu12340** [comment]
> server keeps response with this msg `('content is ', '{"Error Message" : "Invalid API KEY. Please retry or visit our documentation to create one FREE https://financialmodelingprep.com/developer/docs"}') `
> I get my api key where should I add it?

I used this site ```https://financialmodelingprep.com``` for getting the stocks details
You could either create an account here ```https://financialmodelingprep.com/developer/docs/``` or you could simply comment out those lines and work on the UI :sweat_smile:

**Comment by annu12340** [comment]
Solved
