### ISSUE TITLE
Add hashing to passwords

### ISSUE THREAD

**Issue by annu12340** [annu12340/CS50-Final-Project#2]
As of now, the passwords are directly saved into the db. However, this is insecure
Use the **```hash()```** in python to hash the passwords and then save it to the db

**Comment by anup-a** [comment]
Hey can I work on this?

**Comment by ChaoticBlack** [comment]
can you explain in which files i'll have to make changes? I can do the rest

**Comment by anup-a** [comment]
Created PR https://github.com/annu12340/CS50-Final-Project/pull/5

- Added argon2 secure hashing (Modern approach over Bcrypt)
- Authenticates hash while login
- Generates hash and store while registering

**Comment by annu12340** [comment]
The issue is solved
