### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by annu12340** [annu12340/CS50-Final-Project#3]
Update the readme file with:-

1. Better description in the readme
2. Installation steps

**Comment by ChaoticBlack** [comment]
I can do it! Assign it to me please

**Comment by UshasriMavuri1999** [comment]
Hey @annu12340 , I would like to work on this... Could you please assign this to me!

**Comment by VanshVarshney** [comment]
Hey @annu12340 I am Expert in writing Markdown Files. Please Assign This to me.

**Comment by annu12340** [comment]
Since @ChaoticBlack asked me first, I am assigning it to him

**Comment by annu12340** [comment]
Solved
